[project]
name = "newsapi-mcp"
version = "0.1.0"
description = "MCP to query CurrentsAPI for the latest news"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "currentsapi>=0.0.2",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
